version: '3.8'
services:
  xtls-reality:
    image: xtls-reality:latest
    build: .
    environment:
      - SNI=www.samsung.com
      - MASTER_SHORT_ID=ab1337cd
    container_name: xtls-reality
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./config:/opt/xray/config